### ISSUE TITLE
Duplicate CSS

### ISSUE THREAD

**Issue by martoio** [conquestfree/prj-rev-bwfs-dasmoto#4]
This same bit of CSS is reused for all of your IDs. Is there anything they have in common that you can exploit to remove this duplicate code?

https://github.com/conquestfree/prj-rev-bwfs-dasmoto/blob/ceb01db43897f70463054ba3e9f1ab0b3fff7adb/Dasmotos/resources/styles/style.css#L27-L34

Hint: you can put a class on your divs or just select the div. Then you put all of the duplicate code (font-size, etc) on that new selector. At the end you should have something like:
```css
div{
     font-size: 32px; 
     font-weight: bold; 
     color: white; 
}

#paint-title{
    background-color: skyblue;
}
```
